spring:
  profiles:
    active: prod
  config:
    import: file:env.properties # env.properties
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
twilio:
  accountSid: ${TWILIO_SID}
  authToken: ${TWILIO_TOKEN}
  trialNumber: ${TWILIO_TRIAL}
  phoneNumberTo: ${TWILIO_TO}  # trial account can send sms only to one verified phone number

logo-path: https://s3.eu-central-1.amazonaws.com/smartfood-project.link/SmartFood2.png
timezone:
  name: Asia/Jerusalem

reservation-duration: 2 # hours
waiting-list:
  reserve-time: 60 # minutes

--- #------------------------------------------------------ dev profile -------------------------------------------------------------#

-spring:
  devtools:
    restart:
      enabled=true:

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant_system #?useSSL=false
    username: root
    password: Aa123456
  jpa:
    hibernate:
      ddl-auto: create-drop #update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # format_sql: true
    show-sql: false
logging:
  level:
    com.restaurant.smartfood: debug
server:
  error:
    include-stacktrace: never

message-service:
  send-emails: false
  default-mail: ${MAIL_USER}   # when send-emails is false, mails will be sent each time to this address instead of the real address
domain-url: http://localhost:3000

--- #------------------------------------------------------ prod profile -------------------------------------------------------------#

domain-url: https://www.smartfood-project.link
message-service:
  send-emails: true # to disable send of emails change to false
  default-mail: ${MAIL_USER} # when send-emails is false, mails will be sent each time to this address instead of the real address
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_AWS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update  #  create-drop  #
    #show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    com.restaurant.smartfood: info
server:
  port: ${PORT:5000}
  error:
    include-stacktrace: never

--- #------------------------------------------------------ test profile -------------------------------------------------------------#

spring:
  config:
    activate:
      on-profile: test
  h2.console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:mem:dcbapp
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop #update

