spring:
  profiles:
    active: dev
timezone:
  name: Asia/Jerusalem

---
-spring:
  devtools:
    restart:
      enabled=true:

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant_system #?useSSL=false
    username: root
    password: Aa123456
  jpa:
    hibernate:
      ddl-auto: create-drop  #  update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
       # format_sql: true
    show-sql: true
logging:
  level:
    com.restaurant.smartfood: trace
server:
  error:
    include-stacktrace: never

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant_system #?useSSL=false
    username: root
    password: Aa123456
    #heroku DB
#    url: jdbc:mysql://eu-cdbr-west-02.cleardb.net/heroku_a04d5356c8040dd
#    username: b90558b4068387
#    password: 41052d61
  jpa:
    hibernate:
      ddl-auto: create-drop #update

    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    com.restaurant.smartfood: info
server:
  #  ssl:
  #    key-store: classpath:springboot.p12
  #    key-store-password: password
  #    key-store-type: pkcs12
  #    key-alias: springboot
  #    key-password: password
  #  port: 8443
  port: 5000
  error:
    include-stacktrace: never
---
spring:
  h2.console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:mem:dcbapp
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  config:
    activate:
      on-profile: test
