spring:
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    username: smartfoood2023@gmail.com
    password: gshwkbcikltxiadv
    port: 587
   #protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

timezone:
  name: Asia/Jerusalem

twilio:
  account_sid: AC1b315bccc304f1b4381e74bca8cf552a
  auth_token: a86348bb72f00041749a34c3c8abac2a #70f2a4a95fb7dbb3a4ad65b8119cca1b
  trial_number: +18123894306
  phone-number-to: +972524453933


domain-url: http://localhost:3000
reservation-duration: 2 # hours
waiting-list:
  reserve-time: 4 # minutes
---
-spring:
  devtools:
    restart:
      enabled=true:

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant_system #?useSSL=false
    username: root
    password: Aa123456
  jpa:
    hibernate:
      ddl-auto: create-drop #update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # format_sql: true
    show-sql: false
logging:
  level:
    com.restaurant.smartfood: debug
server:
  error:
    include-stacktrace: never

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://smartfood-db.cfveqwj8ivr1.eu-central-1.rds.amazonaws.com:3306/sys
    username: admin
    password: Aa123456
    #heroku DB
  #    url: jdbc:mysql://eu-cdbr-west-02.cleardb.net/heroku_a04d5356c8040dd
  #    username: b90558b4068387
  #    password: 41052d61
  jpa:
    hibernate:
      ddl-auto: update   #create-drop

    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    com.restaurant.smartfood: info
server:
  #  ssl:
  #    key-store: classpath:springboot.p12
  #    key-store-password: password
  #    key-store-type: pkcs12
  #    key-alias: springboot
  #    key-password: password
  #  port: 8443
  port: 5000
  error:
    include-stacktrace: never
---
spring:
  h2.console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:mem:dcbapp
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  config:
    activate:
      on-profile: test
